# Experiment

## Import libraries

In [145]:
import pandas as pd

In [146]:
file_path = "vietstock_2000_2025.csv"

In [147]:
df = pd.read_csv(file_path)

In [148]:
df

,Chỉ tiêu,Đơn vị tính,Tháng 1/2009,Tháng 2/2009,Tháng 3/2009,Tháng 4/2009,Tháng 5/2009,Tháng 6/2009,Tháng 7/2009,Tháng 8/2009,...,Tháng 8/2024,Tháng 9/2024,Tháng 10/2024,Tháng 11/2024,Tháng 12/2024,Tháng 1/2025,Tháng 2/2025,Tháng 3/2025,Tháng 4/2025,Đồ thị
0,Chỉ số giá tiêu dùng,%,0.32,1.17,-0.17,0.35,0.44,0.55,0.52,0.24,...,0.00,0.29,0.33,0.13,0.29,0.98,0.34,-0.03,0.07,NaN
1,Hàng ăn và dịch vụ ăn uống,%,0.39,1.67,-0.46,0.43,0.18,0.28,-0.05,-0.08,...,0.27,0.92,0.55,-0.22,-0.13,0.74,0.43,-0.05,0.12,NaN
2,Lương thực,%,-0.04,0.82,1.27,0.03,-0.37,-1.10,-0.92,-0.42,...,0.19,0.77,0.77,0.33,0.26,0.30,-0.24,-0.83,-0.65,NaN
3,Thực phẩm,%,0.55,1.72,-1.55,0.46,0.36,0.67,-0.05,-0.09,...,0.28,1.06,0.66,-0.50,-0.30,0.97,0.41,0.08,0.17,NaN
4,Ăn uống ngoài gia đình,%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.26,0.65,0.19,0.26,0.14,0.33,0.75,-0.03,0.32,NaN
5,Đồ uống và thuốc lá,%,1.89,0.80,0.35,0.45,0.31,0.64,0.47,0.11,...,0.15,0.03,0.11,0.26,0.20,0.69,0.12,-0.04,0.11,NaN
6,"May mặc, giày dép mũ nón",%,1.46,0.44,0.19,0.20,0.26,0.47,0.29,0.52,...,0.05,0.15,0.09,0.21,0.28,0.38,-0.11,0.05,0.06,NaN
7,Nhà ở và vật liệu xây dựng,%,0.77,1.59,0.30,0.45,0.97,1.45,1.89,0.93,...,0.29,0.52,0.11,0.87,0.53,0.35,0.55,0.50,0.62,NaN
8,Thiết bị và đồ dùng gia đình,%,0.61,0.70,0.34,0.28,0.51,0.66,0.37,0.30,...,0.09,0.14,0.20,0.08,0.17,0.31,0.05,0.13,0.10,NaN
9,Thuốc và dịch vụ y tế,%,0.47,0.36,0.29,0.24,0.18,0.27,0.36,0.16,...,0.18,0.05,0.02,0.05,2.19,9.47,0.31,0.13,0.02,NaN
10,Giao thông,%,-3.51,-0.05,-0.55,0.48,1.80,1.35,3.05,1.31,...,-1.98,-2.77,0.66,-0.07,0.57,0.95,0.63,-1.41,-1.05,NaN
11,Bưu chính viễn thông,%,-1.81,-1.08,0.00,-0.04,1.92,-3.80,-0.37,-0.04,...,0.15,0.09,-0.05,-0.30,-0.03,-0.12,-0.03,0.02,-0.15,NaN
12,Giáo dục,%,0.07,0.04,0.09,0.10,0.04,0.07,0.21,0.15,...,0.14,2.09,0.48,0.11,0.16,-0.04,0.02,0.02,0.00,NaN
13,"Văn hóa, giải trí và du lịch",%,1.66,-0.07,-0.12,-0.64,0.03,0.30,0.45,0.12,...,0.12,-0.24,0.09,0.20,0.20,0.27,0.17,0.18,0.01,NaN
14,Đồ dùng và dịch vụ khác,%,1.93,2.01,0.26,0.38,1.44,1.36,0.45,0.40,...,0.20,0.24,0.26,0.29,0.22,0.51,0.18,0.21,0.15,NaN

In [149]:
df = df.drop(df.columns[:2], axis=1)
df = df.transpose()
df.columns = [
    "cpi",
    "fnb_services",
    "staple_food",
    "food",
    "fafh",
    "drink_and_tobaco",
    "wearing",
    "housing_and_building_materials",
    "household_appliances_and_equipment",
    "medicines_and_medical_services",
    "traffic",
    "post_and_telecommunications",
    "education",
    "culture_entertainment_and_tourism",
    "other_supplies_and_services",
]
df['Month'] = df.index.to_series().str.extract(r'Tháng (\d+)/\d+')[0].astype('Int64')
df['Year'] = df.index.to_series().str.extract(r'Tháng \d+/(\d+)')[0].astype('Int64')
df = df[['Year', 'Month'] + [col for col in df.columns if col not in ['Year', 'Month']]]
df = df.reset_index(drop=True)
df

,Year,Month,cpi,fnb_services,staple_food,food,fafh,drink_and_tobaco,wearing,housing_and_building_materials,household_appliances_and_equipment,medicines_and_medical_services,traffic,post_and_telecommunications,education,culture_entertainment_and_tourism,other_supplies_and_services
0,2009,1,0.32,0.39,-0.04,0.55,NaN,1.89,1.46,0.77,0.61,0.47,-3.51,-1.81,0.07,1.66,1.93
1,2009,2,1.17,1.67,0.82,1.72,NaN,0.80,0.44,1.59,0.70,0.36,-0.05,-1.08,0.04,-0.07,2.01
2,2009,3,-0.17,-0.46,1.27,-1.55,NaN,0.35,0.19,0.30,0.34,0.29,-0.55,0.00,0.09,-0.12,0.26
3,2009,4,0.35,0.43,0.03,0.46,NaN,0.45,0.20,0.45,0.28,0.24,0.48,-0.04,0.10,-0.64,0.38
4,2009,5,0.44,0.18,-0.37,0.36,NaN,0.31,0.26,0.97,0.51,0.18,1.80,1.92,0.04,0.03,1.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,2025,1,0.98,0.74,0.30,0.97,0.33,0.69,0.38,0.35,0.31,9.47,0.95,-0.12,-0.04,0.27,0.51
193,2025,2,0.34,0.43,-0.24,0.41,0.75,0.12,-0.11,0.55,0.05,0.31,0.63,-0.03,0.02,0.17,0.18
194,2025,3,-0.03,-0.05,-0.83,0.08,-0.03,-0.04,0.05,0.50,0.13,0.13,-1.41,0.02,0.02,0.18,0.21
195,2025,4,0.07,0.12,-0.65,0.17,0.32,0.11,0.06,0.62,0.10,0.02,-1.05,-0.15,0.00,0.01,0.15
196,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN