# Experiment

## Import libraries

In [26]:
import pandas as pd

In [27]:
file_path = "worldometer_2000_2025.csv"

In [28]:
df = pd.read_csv(file_path)

In [29]:
df

,Year,GDP Nominal(Current USD),GDP Real(Inflation adj.),GDPChange,GDP percapita,Pop.Change,Population
0,2023,"$429,717,000,000","$377,364,000,000",5.05%,"$3,760",0.67%,"100,352,192"
1,2022,"$410,324,000,000","$359,236,000,000",8.12%,"$3,604",0.75%,"99,680,655"
2,2021,"$366,475,000,000","$332,246,000,000",2.55%,"$3,358",0.87%,"98,935,098"
3,2020,"$346,616,000,000","$323,972,000,000",2.87%,"$3,303",0.93%,"98,079,191"
4,2019,"$334,365,000,000","$314,948,000,000",7.36%,"$3,241",0.97%,"97,173,776"
5,2018,"$310,106,000,000","$293,359,000,000",7.46%,"$3,048",1.11%,"96,237,319"
6,2017,"$281,354,000,000","$272,981,000,000",6.94%,"$2,868",1.25%,"95,176,977"
7,2016,"$257,096,000,000","$255,265,000,000",6.69%,"$2,716",1.27%,"94,000,117"
8,2015,"$239,258,000,000","$239,258,000,000",6.99%,"$2,578",1.25%,"92,823,254"
9,2014,"$233,451,000,000","$223,633,000,000",6.42%,"$2,439",1.22%,"91,679,578"
10,2013,"$213,709,000,000","$210,137,000,000",5.55%,"$2,320",1.19%,"90,573,104"
11,2012,"$195,591,000,000","$199,081,000,000",5.5%,"$2,224",1.18%,"89,510,356"
12,2011,"$172,595,000,000","$188,694,000,000",6.41%,"$2,133",1.16%,"88,468,314"
13,2010,"$147,201,000,000","$177,322,000,000",6.42%,"$2,028",1.15%,"87,455,152"
14,2009,"$106,015,000,000","$166,620,000,000",5.4%,"$1,927",1.51%,"86,460,018"
15,2008,"$99,130,304,099","$158,087,000,000",5.66%,"$1,856",1.84%,"85,175,788"
16,2007,"$77,414,425,532","$149,616,000,000",7.13%,"$1,789",1.78%,"83,633,375"
17,2006,"$66,371,664,817","$139,659,000,000",6.98%,"$1,700",1.33%,"82,167,897"
18,2005,"$57,633,255,738","$130,549,000,000",7.55%,"$1,610",0.93%,"81,088,313"
19,2004,"$45,427,854,693","$121,388,000,000",7.54%,"$1,511",0.97%,"80,338,971"
20,2003,"$39,552,513,232","$112,881,000,000",6.9%,"$1,419",1%,"79,563,777"
21,2002,"$35,064,105,501","$105,595,000,000",6.32%,"$1,341",1.03%,"78,772,224"
22,2001,"$32,685,198,809","$99,317,782,863",6.19%,"$1,274",1.06%,"77,969,361"
23,2000,"$31,172,518,403","$93,525,828,109",6.79%,"$1,212",1.14%,"77,154,011"
24,1999,"$28,683,659,007","$87,581,401,292",4.77%,"$1,148",1.31%,"76,287,452"
25,1998,"$27,209,602,050","$83,591,107,164",5.76%,"$1,110",1.45%,"75,299,660"
26,1997,"$26,843,700,442","$79,035,160,538",8.15%,"$1,065",1.46%,"74,226,889"
27,1996,"$24,657,470,575","$73,077,797,034",9.34%,$999,1.54%,"73,156,447"
28,1995,"$20,736,164,459","$66,835,362,482",9.54%,$928,1.69%,"72,049,940"
29,1994,"$16,286,433,533","$61,014,304,827",8.84%,$861,1.82%,"70,854,391"
30,1993,"$13,180,953,598","$56,059,239,339",8.07%,$806,1.94%,"69,586,384"

In [30]:
df = df.iloc[:, [0, 3]]
df.columns = [
    "year",
    "gdp_true_growth_acc",
]
df = df[df["year"] >= 2000]
df.insert(1, "quarter", 4)
df["gdp_true_growth_acc"] = df["gdp_true_growth_acc"].str.rstrip("%").astype(float)
df

    year  quarter  gdp_true_growth_acc
0   2023        4                 5.05
1   2022        4                 8.12
2   2021        4                 2.55
3   2020        4                 2.87
4   2019        4                 7.36
5   2018        4                 7.46
6   2017        4                 6.94
7   2016        4                 6.69
8   2015        4                 6.99
9   2014        4                 6.42
10  2013        4                 5.55
11  2012        4                 5.50
12  2011        4                 6.41
13  2010        4                 6.42
14  2009        4                 5.40
15  2008        4                 5.66
16  2007        4                 7.13
17  2006        4                 6.98
18  2005        4                 7.55
19  2004        4                 7.54
20  2003        4                 6.90
21  2002        4                 6.32
22  2001        4                 6.19
23  2000        4                 6.79