# Experiment

## Import libraries

In [150]:
import pandas as pd

In [151]:
file_path = "vietstock_2000_2025.csv"

In [152]:
df = pd.read_csv(file_path)

In [153]:
df

,Chỉ tiêu,Đơn vị tính,15/01/2011,30/01/2011,15/02/2011,28/02/2011,15/03/2011,30/03/2011,15/04/2011,29/04/2011,...,12/05/2025,13/05/2025,14/05/2025,15/05/2025,16/05/2025,17/05/2025,19/05/2025,20/05/2025,21/05/2025,Đồ thị
0,Tỷ giá trung tâm (từ 04/01/2016),VNĐ/USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"24,945","24,973","24,973","24,970","24,960","24,960","24,970","24,968","24,962",NaN
1,Liên ngân hàng,VNĐ/USD,"18,932","18,932","20,703","20,673","20,663","20,698","20,723","20,698",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
df = df.drop(df.columns[:2], axis=1).drop(df.columns[-1], axis=1)
df = df.transpose()
df.index = pd.to_datetime(df.index, format="%d/%m/%Y")
df = df.reset_index()
df = df.rename(columns={"index": "date"})
df["exchange_rate"] = df[0].combine_first(df[1])
df = df.drop(columns=[0, 1])
df["exchange_rate"] = (
    df["exchange_rate"].str.replace(",", ".", regex=True).astype(float)
)
df["date"] = pd.to_datetime(df["date"], format="%Y/%m/%d").dt.date

df

            date  exchange_rate
0     2011-01-15         18.932
1     2011-01-30         18.932
2     2011-02-15         20.703
3     2011-02-28         20.673
4     2011-03-15         20.663
...          ...            ...
3273  2025-05-16         24.960
3274  2025-05-17         24.960
3275  2025-05-19         24.970
3276  2025-05-20         24.968
3277  2025-05-21         24.962

[3278 rows x 2 columns]