# Visualization

## Import libraries

In [6]:
import os

from visualizer.visualizer import Visualizer
from utils.constants import SCRAPER_START_DATE, SCRAPER_END_DATE
from utils.enums import GenerateDateTimeType

In [7]:
my_visualizer = Visualizer()
my_visualizer.connect_to_database(database_name=os.getenv("SILVER_POSTGRES_DATABASE"))

## silver_gdp

In [8]:
silver_gdp = my_visualizer.select(schema_name="macroeconomics", table_name="gdp")
silver_gdp

    year  quarter  agriculture  industry  services  gdp_growth   gdp_real
0   2005        1          NaN       NaN       NaN        7.20        NaN
1   2006        1          NaN       NaN       NaN        7.20        NaN
2   2007        1          NaN       NaN       NaN        7.70        NaN
3   2008        1          NaN       NaN       NaN        7.43        NaN
4   2008        2          NaN       NaN       NaN        5.70        NaN
5   2009        1          NaN       NaN       0.0        3.10        NaN
6   2010        1          0.0       0.0       0.0        5.83        0.0
7   2011        1          0.0       NaN       NaN        5.43        NaN
8   2011        2          0.0       0.0       0.0        5.67        0.0
9   2011        3          NaN       NaN       NaN        6.07        NaN
10  2012        1          NaN       NaN       NaN        4.00        NaN
11  2013        1      65298.0  192430.0  222727.0        4.76   480455.0
12  2013        2     138831.0  230162.0  245909.0        5.00   614902.0
13  2013        3     109506.0  241824.0  292298.0        5.54   643601.0
14  2013        4     133399.0  316673.0  354528.0        6.04   804599.0
15  2014        1      66844.0  200860.0  235979.0        5.06   503683.0
16  2015        1      66940.0  184644.0  216604.0        6.03   534573.0
17  2016        1      66186.0  197759.0  229578.0        5.46   564255.0
18  2017        1      49119.0  206847.0  244194.0        5.10   593170.0
19  2017        2     117499.0  189759.0  278136.0        6.17   775495.0
20  2017        3      83555.0  235636.0  334750.0        7.46   836270.0
21  2018        1      70244.0  227596.0  260157.0        7.38   637244.0
22  2018        2     223482.0  826087.5  558608.0        6.79  2358942.5
23  2018        3     345561.1  513350.0  915734.7        6.88  1466960.0
24  2018        4     154845.0  415876.0  440185.0        7.31  1134963.0
25  2019        1      72261.0  247733.0  276919.0        6.79   681010.0
26  2019        2     156090.0  311394.0  318984.0        6.71   884508.0
27  2019        3     124487.0  344648.0  381359.0        7.31   957109.0
28  2019        4     157354.0  448832.0  475814.0        6.97  1214052.0
29  2020        1      72406.0  260602.0  285964.0        3.82   707223.0
30  2020        2     158542.0  315686.0  313378.0        0.36   887862.0
31  2020        3     128735.0  355168.0  392479.0        2.62   983730.0
32  2020        4     164726.0  473978.0  496223.0        4.48  1268385.0
33  2021        1     125510.0  434967.0  508697.0        4.48  1189216.0
34  2021        2     137147.0  478718.0  515232.0        6.61  1248813.0
35  2021        3     156017.0  450933.0  481371.0       -6.17  1201066.0
36  2021        4     157234.0  547529.0  634633.0        5.22  1467490.0
37  2022        1     130990.0  462710.0  535754.0        5.03  1255312.0
38  2022        2     141144.0  521538.0  558903.0        7.72  1346821.0
39  2022        3     148123.0  516567.0  587647.0       13.67  1376321.0
40  2022        4     178958.0  562396.0  666854.0        5.92  1538951.0
41  2023        1     140836.0  459243.0  590817.0        3.32  1320755.0
42  2023        2     143521.0  512383.0  623253.0        4.14  1407473.0
43  2023        3     154316.0  539924.0  626848.0        5.33  1450322.0
44  2023        4     184545.0  605975.0  716362.0        6.72  1643902.0
45  2024        1     145600.0  488208.0  627420.0        5.66  1396660.0
46  2024        2     151303.0  545237.0  677030.0        6.93  1508387.0
47  2024        3     161767.0  588545.0  680490.0        7.43  1567923.0
48  2024        4     192991.0  657896.0  776143.0        7.55  1773652.0
49  2025        1     153001.0  526666.0  681303.0        6.93  1502807.0
50  2025        2     156992.0  599879.0  742776.0        7.96  1643317.0

In [9]:
std_silver_gdp = my_visualizer.make_date_time_index_for_dataframe(silver_gdp)
std_silver_gdp

          date  agriculture  industry  services  gdp_growth   gdp_real
0   2000-03-31          NaN       NaN       NaN         NaN        NaN
1   2000-06-30          NaN       NaN       NaN         NaN        NaN
2   2000-09-30          NaN       NaN       NaN         NaN        NaN
3   2000-12-31          NaN       NaN       NaN         NaN        NaN
4   2001-03-31          NaN       NaN       NaN         NaN        NaN
..         ...          ...       ...       ...         ...        ...
97  2024-06-30     151303.0  545237.0  677030.0        6.93  1508387.0
98  2024-09-30     161767.0  588545.0  680490.0        7.43  1567923.0
99  2024-12-31     192991.0  657896.0  776143.0        7.55  1773652.0
100 2025-03-31     153001.0  526666.0  681303.0        6.93  1502807.0
101 2025-06-30     156992.0  599879.0  742776.0        7.96  1643317.0

[102 rows x 6 columns]

In [10]:
std_silver_gdp_fig = my_visualizer.plot_line_chart(
    std_silver_gdp,
    x_column="date",
    y_columns=["gdp_growth"],
    title="GDP Growth",
    y_axis_title="Rate",
    y_unit="%",
)
std_silver_gdp_fig